# Generated by Django 3.2.21 on 2023-10-17 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20231017_1321'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='Search',
        ),
    ]
