# Generated by Django 3.2.21 on 2023-10-17 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_rename_product_search'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Search',
            new_name='Blog',
        ),
    ]
